name: multi-line
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: echo list read
        run: |
          echo "multi-line"
          ls -lrta
          cat README.md
      - name: installing cowsay
        run: sudo apt-get install cowsay -y
      - name: cowsay
        run: cowsay -f dragon "I am dragon" >> dragon.txt
      - name: check file
        run: grep -i "dragon" dragon.txt
      - name: display
        run: cat dragon.txt
      - name: list 
        run: ls -lrta
        